import { ACCESS } from './role.config';
import { ERole } from './role.config';

export const ROLE_PERMISSIONS = {
  [ERole.ADMINISTRATOR]: [
    ACCESS.CREATE_USER,
    ACCESS.LIST_USER,
    ACCESS.VIEW_USER,
    ACCESS.UPDATE_USER,
    ACCESS.DELETE_USER,
    ACCESS.SOFT_DELETE_USER,
    ACCESS.RESTORE_USER,

    // Role Module
    ACCESS.LIST_ROLE,
    ACCESS.LIST_PERMISSION,
    ACCESS.CREATE_ROLE,
    ACCESS.UPDATE_ROLE,
    ACCESS.DELETE_ROLE,
    // ACCESS.CREATE_PRODUCT,
    // // ACCESS.UPDATE_PRODUCT,
    // ACCESS.DELETE_PRODUCT,
    // ACCESS.LIST_PRODUCT,
    // ACCESS.VIEW_PRODUCT,
    // ACCESS.CHECK_REVENUE,
    // // brand permissions
    // ACCESS.CREATE_BRAND,
    // ACCESS.UPDATE_BRAND,
    // ACCESS.DELETE_BRAND,
    // ACCESS.LIST_BRAND,
    // ACCESS.VIEW_BRAND,
    // // category permissions
    // ACCESS.CREATE_CATEGORY,
    // ACCESS.UPDATE_CATEGORY,
    // ACCESS.DELETE_CATEGORY,
    // ACCESS.LIST_CATEGORY,
    // ACCESS.VIEW_CATEGORY,
    // // discount permissions
    // ACCESS.CREATE_DISCOUNT,
    // ACCESS.UPDATE_DISCOUNT,
    // ACCESS.DELETE_DISCOUNT,
    // ACCESS.LIST_DISCOUNT,
    // ACCESS.VIEW_DISCOUNT,
    // // product detail permissions
    // ACCESS.CREATE_PRODUCT_DETAIL,
    // ACCESS.UPDATE_PRODUCT_DETAIL,
    // ACCESS.DELETE_PRODUCT_DETAIL,
    // ACCESS.LIST_PRODUCT_DETAIL,
    // ACCESS.VIEW_PRODUCT_DETAIL,
    // // product price history permissions
    // ACCESS.CREATE_PRODUCT_PRICE_HISTORY,
    // ACCESS.UPDATE_PRODUCT_PRICE_HISTORY,
    // ACCESS.DELETE_PRODUCT_PRICE_HISTORY,
    // ACCESS.VIEW_PRODUCT_PRICE_HISTORY,
    // Other Admin rights...
  ],
  [ERole.GUEST]: [
    // ACCESS.LIST_PRODUCT,
    // ACCESS.VIEW_PRODUCT,
    // ACCESS.LIST_BRAND,
    // ACCESS.VIEW_BRAND,
    // ACCESS.LIST_CATEGORY,
    // ACCESS.VIEW_CATEGORY,
    // ACCESS.LIST_DISCOUNT,
    // ACCESS.VIEW_DISCOUNT,
    // ACCESS.LIST_PRODUCT_DETAIL,
    // ACCESS.VIEW_PRODUCT_DETAIL,
    // Other Guest rights...
  ],
  // Other roles...
};
